# Шрифт 
font_family Fira Code
bold_font auto
italic_font auto
bold_italic_font auto
font_size 16.0
# disable_ligatures cursor

# Конфигурация окна 
# Sets the initial height to 30 columns.
initial_window_height 30c
# Sets the initial width to 100 columns.
initial_window_width 100c
# Do not remember the window position.
remember_window_position no
# Do not remember the  window size.
remember_window_size no
# Подтверждение
confirm_os_window_close 0
# Прозрачность
# background_opacitity 0.5
# dynamic_background_opacity yes

# Внутренние отступы
window_padding_width 5 

# Конфигурации уведомлений
# Disables the annoying terminal beep.
enable_audio_bell no
# Send a notification when unfocused.
notify_on_cmd_finish unfocused 10.0 command notify-send "job finished with status: %s" %c

# Конфигурации оболочки
# Number of lines to keep in history.
scrollback_lines 2000
# Enables shell integration.
# shell_integration enabled


# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME
